# Generated by Django 2.2.5 on 2019-11-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Pant'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
