# Generated by Django 2.2.5 on 2019-11-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191128_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('AL', 'Analgesics'), ('AT', 'Antacids'), ('AD', 'Antianxiety Drugs'), ('AA', 'Antiarrhythmics'), ('AB', 'Antibacterials'), ('AC', 'Antibiotics'), ('CT', 'Anticoagulants and Thrombolytics'), ('AC', 'Anticonvulsants'), ('TD', 'Antidepressants'), ('DA', 'Antidiarrheals'), ('AM', 'Antiemetics'), ('AF', 'Antifungals'), ('AH', 'Antihistamines'), ('HP', 'Antihypertensives'), ('AI', 'Anti-Inflammatories'), ('AN', 'Antineoplastics'), ('PC', 'Antipsychotics'), ('AP', 'Antipyretics'), ('AV', 'Antivirals'), ('B', 'Barbiturates'), ('BB', 'Beta-Blockers'), ('BC', 'Bronchodilators'), ('CC', 'Cold Cures'), ('CT', 'Corticosteroids'), ('CS', 'Cough Suppressants'), ('C', 'Cytotoxics'), ('DC', 'Decongestants'), ('D', 'Diuretics'), ('E', 'Expectorant'), ('H', 'Hormones'), ('HG', 'Hypoglycemics'), ('I', 'Immunosuppressives'), ('L', 'Laxatives'), ('MR', 'Muscle Relaxants'), ('S', 'Sedatives'), ('SF', 'Sex Hormones(Female)'), ('SM', 'Sex Hormones(Male)'), ('SD', 'Sleeping Drugs'), ('T', 'Tranquilizer'), ('V', 'Vitamins')], max_length=2),
        ),
    ]
