# Generated by Django 2.2.5 on 2020-01-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ('name',), 'verbose_name': 'post_category', 'verbose_name_plural': 'post categories'},
        ),
    ]
