# Generated by Django 2.2.5 on 2020-01-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200113_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ('name',), 'verbose_name': 'post_category', 'verbose_name_plural': 'categories'},
        ),
    ]
